[package]
name = "scheduling-iam"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
anyhow = "1.0.95"
async-trait = "0.1.88"
async_once = "0.2.6"
chrono = "0.4.40"
derive_builder = "0.20.2"
lazy_static = "1.5.0"
rand = "0.9.0"
sqlx = { version = "0.8.3", features = [
    "chrono",
    "postgres",
    "runtime-tokio",
    "uuid",
] }
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }
thiserror = "2.0.11"
time = "0.3.41"
tokio = "1.44.2"
uuid = { version = "1.13.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
validator = { version = "0.20.0", features = ["derive"] }

[lints.rust]
unused = "allow"
