name: Main

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test cargo project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-binstall
      - run: rustup update stable && rustup default stable
      - run: cargo binstall cargo-nextest
      - run: cargo build --verbose
      - run: cargo nextest run --verbose
  formatting:
    name: Check formatting with cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check
  clippy:
    name: Lint with cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy -- -D warnings
