name: Security audit with cargo-audit for scheduling-iam

on:
  workflow_dispatch:
  pull_request:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/security.yml'
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/security.yml'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}